sudo: false
language: java
before_install:
  cp -a /home/travis/build/bob80333/Robot2K16_1251/2016\ Robot/src /home/travis/build/bob80333/Robot2K16_1251/src
install: git clone https://github.com/bob80333/wpilib-mirror.git ~/wpilib
script: 
 - "ant jar"
# - "ant test"
# - "cd /home/travis/build/bob80333/Robot2K16_1251/report/junit/xml && ls"
# - "cat TEST-org.usfirst.frc.team1251.robot.SwerveDriveTest.xml"
jdk: oraclejdk8
